### PR TITLE
update tailscale to latest

### PR DESCRIPTION
**Pull request by ClayKaiser**

### CODE REVIEW

**Comment by sztanpet** [comment]
Is this add-on dead?

**Comment by erlendr** [comment]
I’m wondering about this as well. It’s super-useful, works well.

**Comment by ClayKaiser** [comment]
Nothing really to change besides pulling new versions when they are released from Tailscale. Could probably add the --advertise-exit-node or --advertise-routes. There is another branch if you are interested.

**Comment by tsujamin** [comment]
Sorry I don't really watch for tailscale updates closely. Would love to automate it if possible just haven't had time yet 😴

**Pull request merged**
