### PR TITLE
Add --snat-subnet-routes flag option to the config

### LINKED ISSUE #53: Add support for the --snat-subnet-routes flag
**Is your feature request related to a problem? Please describe.**
In order to get [site-to-site networking](https://tailscale.com/kb/1214/site-to-site/) to work, Tailscale needs to be started with the --snat-subnet-routes flag.

**Describe the solution you'd like**
Add a toggle for the snat-subnet-routes flag to the addon’s configuration page.

**Describe alternatives you've considered**
Have tried the official Tailscale addon and it doesn’t seem to work.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by jordiorlando**
Untested as of yet, will update this description once it’s been tested.

Closes #53

### CODE REVIEW

**Comment by tsujamin** [comment]
sounds good let me know when good to merge, just on holiday so j might be a bit slow 🙏

**Comment by oliver-simmons** [comment]
hi @tsujamin do you know when the "--snat-subnet-routes" will be merged and released? I too have the requirement to setup site to site networking which is failing because the --snat-subnet-routes setting is required, thanks.

**Comment by tsujamin** [comment]
Hey mate - I was waiting on the contributor to say when it was good to merge. If you feel like providing some testing of their change maybe add their forked repo to your HA addons and test the option in their build for a while?

Just need docco added for the option too then will be good yo merge

**Comment by freshfieldx** [comment]
@jordiorlando Did your PR work?

**Comment by jordiorlando** [comment]
Sorry for the delayed reply, but it didn't work. My guess is because, as per https://tailscale.com/kb/1019/subnets/, IP forwarding must be enabled on the root OS. I don't really know how to make that happen, or whether that's a terrible idea for Home Assistant. So this definitely needs more work, unfortunately it's not as simple as just adding the flag.

image

**Comment by Gyosa3** [comment]
Hi I am trying things around with the addon and I think your issue is not related to the snat flag itself. I am running the router node on the add-on and it was not working until I enabled the userspace_networking flag.

Once this flag is enabled, the router node works very well, also the exit node. I did not have to change anything at the host OS level.

I believe that the snat flag is just changing the originating IP address from the nated router node IP to the original caller IP, and it should not be linked to the IP forwarding capability, which, in the kb extract you quote above, seems to be related to the routing node itself, not the snat function.

Things do not seem to be that easy anyway, so there is nothing better than testing more. I'll change my version of the addon manually to introduce your change in my setup and will conduct some testing next week, see if I can manage to make it work one way or the other with the right combination of parameters.

**Comment by Gyosa3** [comment]
Hi again,
I've setup a new local version of the add-on that disables snat using the code of this pull request, and it seems to "work" for me, at least I can still do everything I was doing before with no issue.
Nevertheless, I was hoping that I would be able to get the source IP of my devices asking for a DNS query but this parameter did not solve my problem.
image
As you can see, the TCP connection is showing the source IP as before, but the UDP connection to the DNS proxy is still issued from 127.0.0.1, not from the source IP. I believe that it is related to the way the DNS query is relayed, not to snat.
For the rest, as I said before, I cannot test with 2 router nodes so I believe further testing is needed in order to validate the actual good behaviour of this option.
For the record I have enabled this option after I had already the following options enabled:
- userspace-networking
- disable_dns
I have removed all other options and tested with and without advertising routes. It does not change anything.
Cannot test any further, hope it helped anyway.
Cheers

**Pull request closed without merging**
